server:
  port: 8085
  forward-headers-strategy: native

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: ${GATEWAY_GLOBALCORS_CORS_CONFIGURATIONS_[/**]_ALLOWED_ORIGINS}
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: fos-auth
          uri: ${GATEWAY_ROUTES_FOS_AUTH_URI}
          predicates:
            - Path=/api/auth/**, /oauth2/**, /login, /logout
          filters:
            - RewritePath=/api/auth/?(?<segment>.*), /api/$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

        - id: fos-core
          uri: ${GATEWAY_ROUTES_FOS_CORE_URI}
          predicates:
            - Path=/api/core/**
          filters:
            - RewritePath=/api/core/?(?<segment>.*), /api/$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
